// Importing in modules from the window.
const Typed  = window.Typed;
const zxcvbn = window.zxcvbn;

// Function to produce the typing animation.
function Animate_Headline() 
{
  const text = ["Welcome to Video-Conferencer!", "Let's get started..."]; 
  var typing = new Typed(".Headline", {
  strings:    text,
  loop:       true,
  startDelay: 30,
  typeSpeed:  100});
}

// Function to verify whether there is an @ symbol in the 
// email address. Returns true if email contains an @ symbol
// and false otherwise.
function Check_Email()
{
  var email = document.getElementById("email").value;

  if (email.indexOf("@") > -1) return true;
  return false;
}

// Function to verify whether the length of the user name 
// is >= 3 characters. Returns true if the username 
// length is >= 3 characters and false otherwise.
function Check_Username() 
{
  var username = document.getElementById("username").value;

  if (username.length >= 3) return true;
  return false;
}

// Function to verify whether the password is of an adequate
// strength, using the zxcvbn password strength estimator.
// We will say that a password is sufficiently strong if 
// log(guesses) >= 4. Returns true if password is strong 
// enough and some feedback to make the password stronger
// otherwise.
function Check_Password() 
{
  var password = document.getElementById("password").value;
  var strength = zxcvbn(password);

  if (strength.guesses_log10 >= 4.0) return true;

  var feedback = [strength.feedback.warning];
  feedback.concat(strength.feedback.suggestions);

  return feedback; 
}

// Function to show the suggestions generated by 
// zxcvbn upon the event of a weak password being entered.
function Show_Suggestions(feedback)
{
  var element = document.getElementById("Suggestion");
  var value   = feedback.join("<br>");
  
  if (value === "") element.style.display = "none";
  else              element.style.display = "block";

  element.innerHTML = value;
}

// Function that will try to create a user account, if
// a suitable username and password is given.
function Try_Create_Account() 
{
  var result_pass = Check_Password();

  if (result_pass !== true) Show_Suggestions(result_pass);
}

Animate_Headline();
